easy_admin:

    entities:
        JobCategory:
            class: App\Entity\JobCategory
            list:
                title: "Liste des secteurs d'activités"
                sort: ['title', 'ASC']
                actions:
                    - {name: 'show', icon: 'eye', label: false, css_class: 'btn btn-primary'}
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
