easy_admin:

    entities:
        News:
            class: App\Entity\News
            list:
                sort: ['createdAt', 'DESC']
                actions:
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
                fields:
                    - {property: 'title', label: 'Titre'}
                    - 'description'
                    - {property: 'createdAt', label: 'Créer le'}
